apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: onboarding-payroll
  namespace: kogito-knative
  labels:
    taxRate: process
    vacationDays: process
    paymentDate: process
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: docker.io/mswiderski/onboarding-payroll:0.1
            env:
            - name: NAMESPACE
              value: "kogito-knative"
